# Generated by Django 5.1.6 on 2025-02-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_battingstatistics_at_bats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstatistics',
            name='org_abbreviation',
            field=models.CharField(default='placeholder3', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitchingstatistics',
            name='org_abbreviation',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
